// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace marketAPI.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20240808142121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Barang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GudangId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HargaBarang")
                        .HasColumnType("numeric");

                    b.Property<int>("JumlahBarang")
                        .HasColumnType("integer");

                    b.Property<string>("KodeBarang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GudangId");

                    b.ToTable("Table_Barang", (string)null);
                });

            modelBuilder.Entity("Gudang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KodeGudang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaGudang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Table_Gudang", (string)null);
                });

            modelBuilder.Entity("Barang", b =>
                {
                    b.HasOne("Gudang", "Gudang")
                        .WithMany()
                        .HasForeignKey("GudangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gudang");
                });
#pragma warning restore 612, 618
        }
    }
}
